### ISSUE TITLE
Cannot load underlying module for 'Alamofire' for ios

### ISSUE THREAD

**Issue by felix-lambert** [ScreebApp/sdk-reactnative#15]
Hello I cannot build the module with xCode I have the following error > `Cannot load underlying module for 'Alamofire'

`The import from Alamofire does not seem to be recognized.`

This is my Podfile...

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '12.0'

target 'company' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!()
  post_install do |installer|
    flipper_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
```

I tried to clean my folder, close open XCode, rebuild. Nothing seems to work. If I remove @screeb/react-native from the project, the build is succeeding.

Please help

**Comment by clement-screeb** [comment]
It seems that **use_frameworks!** instruction is mandatory in Podfile (see Example app in this repository). I update the documentation

**Comment by clement-screeb** [comment]
It is possible not to set "use_frameworks!" because it runs other issues.
With [this plugin](https://github.com/joncardasis/cocoapods-user-defined-build-types) declared in your Podfile, it runs good.
```ruby
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!
```

Just add this line in target : 
```ruby
pod "Screeb", :build_type => :dynamic_framework
```
 
In attach below a example Podfile

[Podfile.txt](https://github.com/ScreebApp/sdk-reactnative/files/9267519/Podfile.txt)
