### ISSUE TITLE
In App Browser freezes on iOS when initSDK is called for the second time

### ISSUE THREAD

**Issue by louiszawadzki** [ScreebApp/sdk-reactnative#62]
# Issue description

Our app can enable users to change country. When this is the case, we are legally required to ask their consent again in the new country. So when a user changes country we call `closeSDK`.
If they give their consent for us to track them with Screeb in the new country, we will call `initSDK` a second time.

If we do this, we see that opening an in-app browsers will prevent the app from receiving any touch event.
As the iOS SDK is closed-source, we were not able to debug this further.

This is a critical issue for us as we are getting negative store reviews of users being stuck on the app. 
If you have any workaround until the issue is fixed, that would also be very valuable to us.

# How to reproduce

- Clone https://github.com/louiszawadzki/ScreebInAppBrowserIssue
- run `npm install`
- run `(cd ios && bundle install)`
- run `(cd ios && bundle exec pod install)`
- Copy the `credentials.local.ts` file into `credentials.ts` and add a valid iOS channel ID.
- Run the app on an iOS simulator or device
- Click on "trigger SDK issue" (this will run a sequence of `initSDK` -> `closeSDK` -> `initSDK`).
- Click on "trigger in app browser"

Expected result: we can interact with the in app browser.

Actual result: no touch event seems to reach the in app browser.

**Comment by Alexays** [comment]
Hi @louiszawadzki, I'm looking at this problem as a priority.
I'll see if I can fix the problem, without you having to update the sdk.

**Comment by louiszawadzki** [comment]
Thanks a lot for the quick answer @Alexays!

**Comment by Alexays** [comment]
I found the problem, and working on a fix, sadly, that require an SDK upgrade.

**Comment by Alexays** [comment]
Just released 2.1.7, tell me, if everything is ok now :)

**Comment by louiszawadzki** [comment]
I did a quick test on the demo project and it is fixed, thanks a lot for the quick release!
